name: webpack Build

on: [push]

jobs:
  type-check:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
      - run: yarn build
